name = "Rummikub"
uuid = "47d89ea4-6705-4a7e-8827-22f5b39d6006"
authors = ["Ronald Remmerswaal <r.a.remmerswaal@rug.nl>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
